version: '2'
services:
  commondb:
    image: hpsoftware/useitwithcsacodar:csadb
    container_name: commondb
    volumes:
     - /src/share:/var/lib/postgresql
    ports:
     - "15432:5432"
    command: bash -c "sleep 30 && service postgresql-9.5 start && tail -f /dev/null"
  ooce:
   image: hpsoftware/useitwithcsacodar:ooce1062
   container_name: ooce
   environment:
    - dockerclient_hostname=vmhostname
    - dockerclient_ipaddress=vmipaddress
   volumes:
    - /src/share:/share
   ports:
    - "18445:8443"
  csa:
   image: hpsoftware/csa:csa47
   container_name: csa
   environment:
    - dockerclient_hostname=vmhostname
    - dockerclient_ipaddress=vmipaddress
    - proxy_host_name=proxyhost
    - proxy_port=proxyport
   volumes:
    - /src/share:/share
   ports:
    - "18444:8444"
    - "18089:8089"
   depends_on:
    - commondb
    - ooce
   command: /bin/bash -c  "sleep 120 && /tmp/csaconfig.sh && tail -f /dev/null"

